const fs = require('node:fs/promises');

/**
 * This is a simple utility file used to clean up the CSS generated by IcoMoon.
 * If you'd like to apply any text replacements, make use of the REPLACE object below.
 * 
 * i: Otherwise, IcoMoon will target all i tags regardless.
 * before & after: Otherwise, IcoMoon will add extra markup for each path.
 * color: We want to inherit the color from the parent element(s) - see buttons example.
 */
async function cleanCSS() {
  const REPLACE = {
    i: [/i {/, 'i[class^="tlgi-"] {'],
    before: [/ .path1:before/gm, ':before'],
    after: [/ .path2:before/gm, ':after'],
    color: [/color:.*\n/gm, '']
  };
  try {
    const filename = './style.css';
    const CSS = await fs.readFile(filename, { encoding: 'utf8' });

    let content = CSS;
    for (const name in REPLACE) {
      const x = REPLACE[name];
      content = content.replace(x[0], x[1]);
      console.log(`Replacing ${name}...`);
    }

    await fs.writeFile(filename, content);
    console.log(`✅ CSS file updated.`);
  } catch (err) {
    console.error(`❗️`, err);
  }
}

cleanCSS();
